# Teclas mapeadas conforme o MAME
# Baseado no arquivo mame\src\osd\modules\input\input_common.h

MAME_UNKNOWN      = 0x00
MAME_ESCAPE       = 0x01
MAME_1            = 0x02
MAME_2            = 0x03
MAME_3            = 0x04
MAME_4            = 0x05
MAME_5            = 0x06
MAME_6            = 0x07
MAME_7            = 0x08
MAME_8            = 0x09
MAME_9            = 0x0A
MAME_0            = 0x0B
MAME_MINUS        = 0x0C    # - on main keyboard
MAME_EQUALS       = 0x0D
MAME_BACK         = 0x0E    # backspace
MAME_TAB          = 0x0F
MAME_Q            = 0x10
MAME_W            = 0x11
MAME_E            = 0x12
MAME_R            = 0x13
MAME_T            = 0x14
MAME_Y            = 0x15
MAME_U            = 0x16
MAME_I            = 0x17
MAME_O            = 0x18
MAME_P            = 0x19
MAME_LBRACKET     = 0x1A
MAME_RBRACKET     = 0x1B
MAME_RETURN       = 0x1C    # Enter on main keyboard
MAME_LCONTROL     = 0x1D
MAME_A            = 0x1E
MAME_S            = 0x1F
MAME_D            = 0x20
MAME_F            = 0x21
MAME_G            = 0x22
MAME_H            = 0x23
MAME_J            = 0x24
MAME_K            = 0x25
MAME_L            = 0x26
MAME_SEMICOLON    = 0x27
MAME_APOSTROPHE   = 0x28
MAME_GRAVE        = 0x29    # accent grave
MAME_LSHIFT       = 0x2A
MAME_BACKSLASH    = 0x2B
MAME_Z            = 0x2C
MAME_X            = 0x2D
MAME_C            = 0x2E
MAME_V            = 0x2F
MAME_B            = 0x30
MAME_N            = 0x31
MAME_M            = 0x32
MAME_COMMA        = 0x33
MAME_PERIOD       = 0x34    # . on main keyboard
MAME_SLASH        = 0x35    # / on main keyboard
MAME_RSHIFT       = 0x36
MAME_MULTIPLY     = 0x37    # * on numeric keypad
MAME_LMENU        = 0x38    # left Alt
MAME_SPACE        = 0x39
MAME_CAPITAL      = 0x3A
MAME_F1           = 0x3B
MAME_F2           = 0x3C
MAME_F3           = 0x3D
MAME_F4           = 0x3E
MAME_F5           = 0x3F
MAME_F6           = 0x40
MAME_F7           = 0x41
MAME_F8           = 0x42
MAME_F9           = 0x43
MAME_F10          = 0x44
MAME_NUMLOCK      = 0x45
MAME_SCROLL       = 0x46    # Scroll Lock
MAME_NUMPAD7      = 0x47
MAME_NUMPAD8      = 0x48
MAME_NUMPAD9      = 0x49
MAME_SUBTRACT     = 0x4A    # - on numeric keypad
MAME_NUMPAD4      = 0x4B
MAME_NUMPAD5      = 0x4C
MAME_NUMPAD6      = 0x4D
MAME_ADD          = 0x4E    # + on numeric keypad
MAME_NUMPAD1      = 0x4F
MAME_NUMPAD2      = 0x50
MAME_NUMPAD3      = 0x51
MAME_NUMPAD0      = 0x52
MAME_DECIMAL      = 0x53    # . on numeric keypad
MAME_OEM_102      = 0x56    # <> or \| on RT 102-key keyboard (Non-U.S.)
MAME_F11          = 0x57
MAME_F12          = 0x58
MAME_F13          = 0x64    #                     (NEC PC98)
MAME_F14          = 0x65    #                     (NEC PC98)
MAME_F15          = 0x66    #                     (NEC PC98)
MAME_KANA         = 0x70    # (Japanese keyboard)
MAME_ABNT_C1      = 0x73    # /? on Brazilian keyboard
MAME_CONVERT      = 0x79    # (Japanese keyboard)
MAME_NOCONVERT    = 0x7B    # (Japanese keyboard)
MAME_YEN          = 0x7D    # (Japanese keyboard)
MAME_ABNT_C2      = 0x7E    # Numpad . on Brazilian keyboard
MAME_NUMPADEQUALS = 0x8D    # = on numeric keypad (NEC PC98)
MAME_PREVTRACK    = 0x90    # Previous Track (DIK_CIRCUMFLEX on Japanese keyboard)
MAME_AT           = 0x91    #                     (NEC PC98)
MAME_COLON        = 0x92    #                     (NEC PC98)
MAME_UNDERLINE    = 0x93    #                     (NEC PC98)
MAME_KANJI        = 0x94    # (Japanese keyboard)
MAME_STOP         = 0x95    #                     (NEC PC98)
MAME_AX           = 0x96    #                     (Japan AX)
MAME_UNLABELED    = 0x97    #                        (J3100)
MAME_NEXTTRACK    = 0x99    # Next Track
MAME_NUMPADENTER  = 0x9C    # Enter on numeric keypad
MAME_RCONTROL     = 0x9D
MAME_MUTE         = 0xA0    # Mute
MAME_CALCULATOR   = 0xA1    # Calculator
MAME_PLAYPAUSE    = 0xA2    # Play / Pause
MAME_MEDIASTOP    = 0xA4    # Media Stop
MAME_VOLUMEDOWN   = 0xAE    # Volume -
MAME_VOLUMEUP     = 0xB0    # Volume +
MAME_WEBHOME      = 0xB2    # Web home
MAME_NUMPADCOMMA  = 0xB3    # , on numeric keypad (NEC PC98)
MAME_DIVIDE       = 0xB5    # / on numeric keypad
MAME_SYSRQ        = 0xB7
MAME_RMENU        = 0xB8    # right Alt
MAME_PAUSE        = 0xC5    # Pause
MAME_HOME         = 0xC7    # Home on arrow keypad
MAME_UP           = 0xC8    # UpArrow on arrow keypad
MAME_PRIOR        = 0xC9    # PgUp on arrow keypad
MAME_LEFT         = 0xCB    # LeftArrow on arrow keypad
MAME_RIGHT        = 0xCD    # RightArrow on arrow keypad
MAME_END          = 0xCF    # End on arrow keypad
MAME_DOWN         = 0xD0    # DownArrow on arrow keypad
MAME_NEXT         = 0xD1    # PgDn on arrow keypad
MAME_INSERT       = 0xD2    # Insert on arrow keypad
MAME_DELETE       = 0xD3    # Delete on arrow keypad
MAME_LWIN         = 0xDB    # Left Windows key
MAME_RWIN         = 0xDC    # Right Windows key
MAME_APPS         = 0xDD    # AppMenu key
MAME_POWER        = 0xDE    # System Power
MAME_SLEEP        = 0xDF    # System Sleep
MAME_WAKE         = 0xE3    # System Wake
MAME_WEBSEARCH    = 0xE5    # Web Search
MAME_WEBFAVORITES = 0xE6    # Web Favorites
MAME_WEBREFRESH   = 0xE7    # Web Refresh
MAME_WEBSTOP      = 0xE8    # Web Stop
MAME_WEBFORWARD   = 0xE9    # Web Forward
MAME_WEBBACK      = 0xEA    # Web Back
MAME_MYCOMPUTER   = 0xEB    # My Computer
MAME_MAIL         = 0xEC    # Mail
MAME_MEDIASELECT  = 0xED    # Media Select

#adicionar isso em uma nova biblioteca!! - aproximadamente 1/60
TEMPO_FRAME = 1/60